<a href="https://colab.research.google.com/github/gotica462/Player_Scouting/blob/test/ML_ensemble.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import zipfile
%matplotlib inline 
import numpy as np 
import scipy as sp 
import matplotlib as mpl
import matplotlib.cm as cm 
import matplotlib.pyplot as plt
import pandas as pd 
import sklearn
import seaborn as sns
import os
import warnings
from collections import Counter
warnings.filterwarnings('ignore')

In [2]:
pip install imblearn

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [3]:
from sklearn.metrics import balanced_accuracy_score
from sklearn.metrics import confusion_matrix
from imblearn.metrics import classification_report_imbalanced

In [4]:
events = pd.read_csv("events.csv")
events.head()

id_odsp   id_event  sort_order  time  \
0  UFot0hit/  UFot0hit1         1.0   2.0   
1  UFot0hit/  UFot0hit2         2.0   4.0   
2  UFot0hit/  UFot0hit3         3.0   4.0   
3  UFot0hit/  UFot0hit4         4.0   7.0   
4  UFot0hit/  UFot0hit5         5.0   7.0   

                                                text  event_type  event_type2  \
0  Attempt missed. Mladen Petric (Hamburg) left f...         1.0         12.0   
1  Corner,  Borussia Dortmund. Conceded by Dennis...         2.0          NaN   
2  Corner,  Borussia Dortmund. Conceded by Heiko ...         2.0          NaN   
3           Foul by Sven Bender (Borussia Dortmund).         3.0          NaN   
4  Gokhan Tore (Hamburg) wins a free kick in the ...         8.0          NaN   

   side         event_team           opponent  ... player_in player_out  \
0   2.0         Hamburg SV  Borussia Dortmund  ...       NaN        NaN   
1   1.0  Borussia Dortmund         Hamburg SV  ...       NaN        NaN   
2   1.0  Borussia Dortmund         Hamburg SV  ...       NaN        NaN   
3   1.0  Borussia Dortmund         Hamburg SV  ...       NaN        NaN   
4   2.0         Hamburg SV  Borussia Dortmund  ...       NaN        NaN   

  shot_place shot_outcome  is_goal  location  bodypart  assist_method  \
0        6.0          2.0      0.0       9.0       2.0            1.0   
1        NaN          NaN      0.0       NaN       NaN            0.0   
2        NaN          NaN      0.0       NaN       NaN            0.0   
3        NaN          NaN      0.0       NaN       NaN            0.0   
4        NaN          NaN      0.0       2.0       NaN            0.0   

   situation  fast_break  
0        1.0         0.0  
1        NaN         0.0  
2        NaN         0.0  
3        NaN         0.0  
4        NaN         0.0  

[5 rows x 22 columns]

In [5]:
events.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 291127 entries, 0 to 291126
Data columns (total 22 columns):
 #   Column         Non-Null Count   Dtype  
---  ------         --------------   -----  
 0   id_odsp        291127 non-null  object 
 1   id_event       291126 non-null  object 
 2   sort_order     291126 non-null  float64
 3   time           291126 non-null  float64
 4   text           291126 non-null  object 
 5   event_type     291126 non-null  float64
 6   event_type2    65067 non-null   float64
 7   side           291126 non-null  float64
 8   event_team     291126 non-null  object 
 9   opponent       291126 non-null  object 
 10  player         274983 non-null  object 
 11  player2        91235 non-null   object 
 12  player_in      15189 non-null   object 
 13  player_out     15199 non-null   object 
 14  shot_place     67841 non-null   float64
 15  shot_outcome   68215 non-null   float64
 16  is_goal        291126 non-null  float64
 17  location       143529 non-nul

In [6]:
#Show data columns

events.columns

Index(['id_odsp', 'id_event', 'sort_order', 'time', 'text', 'event_type',
       'event_type2', 'side', 'event_team', 'opponent', 'player', 'player2',
       'player_in', 'player_out', 'shot_place', 'shot_outcome', 'is_goal',
       'location', 'bodypart', 'assist_method', 'situation', 'fast_break'],
      dtype='object')

In [7]:
# Find out the values of the "is goal column"
events["is_goal"].unique()

array([ 0.,  1., nan])

In [8]:
#find out the count of "is goal golumn"
events["is_goal"].value_counts()

0.0    283895
1.0      7231
Name: is_goal, dtype: int64

In [9]:
# Reading the dictionary data to see what event type are 

dictionary_text = open('dictionary.txt')

In [10]:
dictionary_text.read()

'event_type\n0\tAnnouncement\n1\tAttempt\n2\tCorner\n3\tFoul\n4\tYellow card\n5\tSecond yellow card\n6\tRed card\n7\tSubstitution\n8\tFree kick won\n9\tOffside\n10\tHand ball\n11\tPenalty conceded\n\n\nevent_type2\n12\tKey Pass\n13\tFailed through ball\n14\tSending off\n15\tOwn goal\n\n\nside\n1\tHome\n2\tAway\n\n\nshot_place\n1\tBit too high\n2\tBlocked\n3\tBottom left corner\n4\tBottom right corner\n5\tCentre of the goal\n6\tHigh and wide\n7\tHits the bar\n8\tMisses to the left\n9\tMisses to the right\n10\tToo high\n11\tTop centre of the goal\n12\tTop left corner\n13\tTop right corner\n\n\nshot_outcome\n1\tOn target\n2\tOff target\n3\tBlocked\n4\tHit the bar\n\n\nlocation\n1\tAttacking half\n2\tDefensive half\n3\tCentre of the box\n4\tLeft wing\n5\tRight wing\n6\tDifficult angle and long range\n7\tDifficult angle on the left\n8\tDifficult angle on the right\n9\tLeft side of the box\n10\tLeft side of the six yard box\n11\tRight side of the box\n12\tRight side of the six yard box\n13\t

In [11]:
encoding = pd.read_table('dictionary.txt',  names=('num','events'))
encoding

num        events
0   event_type           NaN
1            0  Announcement
2            1       Attempt
3            2        Corner
4            3          Foul
..         ...           ...
70   situation           NaN
71           1     Open play
72           2     Set piece
73           3        Corner
74           4     Free kick

[75 rows x 2 columns]

In [12]:
## checking the events column
events["event_type"].unique()

array([ 1.,  2.,  3.,  8., 10.,  7.,  9.,  4.,  6., 11., nan])

In [13]:
#find out the count of "event_type"
events["event_type"].value_counts()

8.0     75117
3.0     73258
1.0     68412
2.0     27153
7.0     15199
9.0     14407
4.0     12377
10.0     3996
11.0      799
6.0       408
Name: event_type, dtype: int64

In [14]:
# We need the is_goal  column for events and the event_type when is equal 1 since that is a shot attempt.
shot_attempts = events[events["event_type"]== 1]

# We check the filter
shot_attempts.head() 

id_odsp    id_event  sort_order  time  \
0   UFot0hit/   UFot0hit1         1.0   2.0   
11  UFot0hit/  UFot0hit12        12.0  14.0   
13  UFot0hit/  UFot0hit14        14.0  17.0   
14  UFot0hit/  UFot0hit15        15.0  19.0   
17  UFot0hit/  UFot0hit18        18.0  20.0   

                                                 text  event_type  \
0   Attempt missed. Mladen Petric (Hamburg) left f...         1.0   
11  Attempt missed. Shinji Kagawa (Borussia Dortmu...         1.0   
13  Goal!  Borussia Dortmund 1, Hamburg 0. Kevin G...         1.0   
14  Attempt blocked. Mats Hummels (Borussia Dortmu...         1.0   
17  Attempt blocked. Tomas Rincon (Hamburg) right ...         1.0   

    event_type2  side         event_team           opponent  ... player_in  \
0          12.0   2.0         Hamburg SV  Borussia Dortmund  ...       NaN   
11         12.0   1.0  Borussia Dortmund         Hamburg SV  ...       NaN   
13         12.0   1.0  Borussia Dortmund         Hamburg SV  ...       NaN   
14          NaN   1.0  Borussia Dortmund         Hamburg SV  ...       NaN   
17          NaN   2.0         Hamburg SV  Borussia Dortmund  ...       NaN   

   player_out shot_place shot_outcome  is_goal  location  bodypart  \
0         NaN        6.0          2.0      0.0       9.0       2.0   
11        NaN       13.0          2.0      0.0      15.0       1.0   
13        NaN        4.0          1.0      1.0       9.0       2.0   
14        NaN        2.0          3.0      0.0      15.0       1.0   
17        NaN        2.0          3.0      0.0      15.0       1.0   

    assist_method  situation  fast_break  
0             1.0        1.0         0.0  
11            1.0        1.0         0.0  
13            1.0        1.0         0.0  
14            0.0        1.0         0.0  
17            0.0        1.0         0.0  

[5 rows x 22 columns]

In [15]:
### We'll check is the number is the same in both databases
shot_attempts["event_type"].value_counts()

1.0    68412
Name: event_type, dtype: int64

In [17]:
# According to our dictionary database there are some shot locations that are not recorded (number 19)
print(shot_attempts.player[shot_attempts.location == 19].count()) 

399


In [18]:
# Let's see the percentage. 
print(shot_attempts.event_type[shot_attempts.location == 19].count()/shot_attempts["event_type"].value_counts()* 100) 

1.0    0.600772
Name: event_type, dtype: float64


In [20]:
#Since is less than 1% we are going to drop those values, even though it may affect our results, it will have a minimal effect

shot_attempts = shot_attempts[shot_attempts.location != 19]


In [21]:
#cHECK NULL VALUIES
shot_attempts.isna().any()

id_odsp          False
id_event         False
sort_order       False
time             False
text             False
event_type       False
event_type2       True
side             False
event_team       False
opponent         False
player           False
player2           True
player_in         True
player_out        True
shot_place        True
shot_outcome     False
is_goal          False
location         False
bodypart         False
assist_method    False
situation        False
fast_break       False
dtype: bool

In [22]:
#Let's start our training and testing
# Create our features
X = shot_attempts[['time', 'side', 'bodypart', 'location', 'situation', 'assist_method', 'fast_break']]

X = pd.get_dummies(X)

# Create our target
y = shot_attempts['is_goal']


In [23]:
X.head()

time  side  bodypart  location  situation  assist_method  fast_break
0    2.0   2.0       2.0       9.0        1.0            1.0         0.0
11  14.0   1.0       1.0      15.0        1.0            1.0         0.0
13  17.0   1.0       2.0       9.0        1.0            1.0         0.0
14  19.0   1.0       1.0      15.0        1.0            0.0         0.0
17  20.0   2.0       1.0      15.0        1.0            0.0         0.0

In [24]:
from sklearn.model_selection import train_test_split
# YOUR CODE HERE
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=1, stratify=y)
X_train.shape

(51000, 7)

In [25]:
X.describe()

time          side      bodypart      location     situation  \
count  68001.000000  68001.000000  68001.000000  68001.000000  68001.000000   
mean      49.025323      1.442082      1.625903     10.282613      1.274069   
std       26.298949      0.496638      0.739399      5.172351      0.697234   
min        0.000000      1.000000      1.000000      3.000000      1.000000   
25%       27.000000      1.000000      1.000000      3.000000      1.000000   
50%       50.000000      1.000000      1.000000     11.000000      1.000000   
75%       72.000000      2.000000      2.000000     15.000000      1.000000   
max       90.000000      2.000000      3.000000     18.000000      4.000000   

       assist_method    fast_break  
count   68001.000000  68001.000000  
mean        1.124881      0.028397  
std         0.989649      0.166104  
min         0.000000      0.000000  
25%         0.000000      0.000000  
50%         1.000000      0.000000  
75%         2.000000      0.000000  
max         4.000000      1.000000

In [26]:
# Check the balance of our target values
y.value_counts()

0.0    61169
1.0     6832
Name: is_goal, dtype: int64

In [28]:
# Balanced Random Forest Classifier

# Resample the training data with the BalancedRandomForestClassifier
from imblearn.ensemble import BalancedRandomForestClassifier
brfc = BalancedRandomForestClassifier(n_estimators=100, random_state=1)

# Fit
brfc.fit(X_train, y_train)
print(X_train.shape)

(51000, 7)


In [29]:
# Calculated the balanced accuracy score
# YOUR CODE HERE
y_pred = brfc.predict(X_test)
balanced_accuracy_score(y_test, y_pred)

0.7022414320369132

In [30]:
#Calculate confusion matrix
cm = confusion_matrix(y_test, y_pred)
cm

array([[10591,  4702],
       [  492,  1216]])

In [31]:
# Print the imbalanced classification report

print(classification_report_imbalanced(y_test, y_pred))

                   pre       rec       spe        f1       geo       iba       sup

        0.0       0.96      0.69      0.71      0.80      0.70      0.49     15293
        1.0       0.21      0.71      0.69      0.32      0.70      0.49      1708

avg / total       0.88      0.69      0.71      0.75      0.70      0.49     17001



In [33]:
# List the features sorted in descending order by feature importance

features_rank = sorted(zip(brfc.feature_importances_, X.columns), reverse=True)
for feature in features_rank:
    print(f"{feature[1]}: ({feature[0]})")

time: (0.4876829828948168)
location: (0.3090580074122709)
assist_method: (0.06610945014124421)
situation: (0.059763537193779095)
fast_break: (0.03165965289188927)
bodypart: (0.02833465863679511)
side: (0.017391710829204626)
